plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '1.0.14'
}

version = mod_version
group = maven_group

base {
    archivesName = archives_base_name
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = neo_version

    runs {
        configureEach {
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
            logLevel = org.slf4j.event.Level.INFO
        }
        client {
            client()
        }
        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

dependencies {
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

jar {
    manifest {
        attributes 'Implementation-Version': project.version
    }

    from('LICENSE') {
        rename { "${it}_${base.archivesName.get()}" }
    }
}

publishing {
    publications {
        create('mavenJava', MavenPublication) {
            artifactId = base.archivesName.get()
            from components.java
        }
    }
}
