pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        maven {
            name = 'TencentCloud'
            url = 'https://mirrors.cloud.tencent.com/nexus/repository/maven-public/'
        }
        maven {
            name = 'Aliyun'
            url = 'https://maven.aliyun.com/repository/public/'
        }
        maven {
            name = 'NeoForge'
            url = 'https://maven.neoforged.net/releases'
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

dependencyResolutionManagement {
    repositories {
        mavenLocal()
        maven {
            name = 'TencentCloud'
            url = 'https://mirrors.cloud.tencent.com/nexus/repository/maven-public/'
        }
        maven {
            name = 'Aliyun'
            url = 'https://maven.aliyun.com/repository/public/'
        }
        maven {
            name = 'NeoForge'
            url = 'https://maven.neoforged.net/releases'
        }
        maven {
            name = 'Minecraft'
            url = 'https://libraries.minecraft.net/'
        }
    }
}

rootProject.name = 'CrosshairBobbingMod'
